# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder ".", "/vagrant", disabled: false
    config.vm.network "forwarded_port", guest: 80, host: 8086

    # config.vm.network "private_network", ip: "192.168.56.10"

    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provision/playbook.yml"
      ansible.verbose = true
    end
  end
  