---
collections:
# With just the collection name
- name: community.general
  type: galaxy
- name: prometheus.prometheus
  type: galaxy
- name: devsec.hardening
  type: galaxy
- name: grafana.grafana
  type: galaxy
  version: ">=2.2.0"
