# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "limarev/centos8-kernel6",
        :ip_addr => '192.168.56.1',
        :disks => {
          :sata1 => {
            :dfile => './storage/sata1.vdi',
            :size => 250,
            :port => 1
          },
          :sata2 => {
            :dfile => './storage/sata2.vdi',
            :size => 250, # Megabytes
            :port => 2
          },
          :sata3 => {
            :dfile => './storage/sata3.vdi',
            :size => 250,
            :port => 3
          },
          :sata4 => {
            :dfile => './storage/sata4.vdi',
            :size => 250, # Megabytes
            :port => 4
          },
          :sata5 => {
            :dfile => './storage/sata5.vdi',
            :size => 250, # Megabytes
            :port => 5
          }
        }
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        needsController = false
		    boxconfig[:disks].each do |dname, dconf|
			    unless File.exist?(dconf[:dfile])
				    vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController =  true
          end
		    end
        if needsController == true
          vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
          boxconfig[:disks].each do |dname, dconf|
              vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
          end
        end
      end
          
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          yum install -y mdadm smartmontools hdparm gdisk
      SHELL
      box.vm.provision "shell", path: "create_raid10.sh"
      box.vm.provision "shell", path: "create_gpt.sh"
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p /etc/mdadm
          touch /etc/mdadm/mdadm.conf
          mdadm --detail --scan --verbose | awk '/ARRAY/ {print}' >> /etc/mdadm/mdadm.conf
        SHELL
    end
  end
end